// Mid-complexity fixture trace used by the dev-only "Load sample" button
// in the Editor toolbar. Touches every Fabric element type at least once
// and has the canonical accept/modify/reject branch off a decisionPoint,
// so it stresses layout, the inspector, drag/connect, and the dirty/sync
// flow without burning an LLM round-trip.
export const sampleTrace = {
  process_name: "AI-Assisted Clinical Note Generation",
  elements: [
    { id: "patient",        type: "humanSource",         name: "Patient" },
    { id: "consult_ui",     type: "ui",                  name: "Telehealth App" },
    { id: "audio",          type: "inputOutput",         name: "Consultation Audio" },
    { id: "transcribe",     type: "fixedAIModel",        name: "Whisper Transcribe" },
    { id: "transcript",     type: "inputOutput",         name: "Transcript" },
    { id: "draft_note",     type: "fixedAIModel",        name: "GPT-4 Note Drafter" },
    { id: "safety_check",   type: "governanceMechanism", name: "Safety + PHI Eval" },
    { id: "review_ui",      type: "ui",                  name: "Clinician Review" },
    { id: "clinician",      type: "humanSource",         name: "Clinician" },
    { id: "decision",       type: "decisionPoint",       name: "Approve note?" },
    { id: "accept_out",     type: "accept",              name: "Accept" },
    { id: "modify_out",     type: "modify",              name: "Edit" },
    { id: "reject_out",     type: "reject",              name: "Reject" },
    { id: "training_loop",  type: "trainingAIModel",     name: "Note Model (RLHF)" },
    { id: "redraft",        type: "restart",             name: "Re-draft" },
    { id: "ehr",            type: "finalOutcome",        name: "Saved to EHR" },
  ],
  flows: [
    { id: "flow_2",  from: "patient",       to: "consult_ui" },
    { id: "flow_3",  from: "consult_ui",    to: "audio" },
    { id: "flow_4",  from: "audio",         to: "transcribe" },
    { id: "flow_5",  from: "transcribe",    to: "transcript" },
    { id: "flow_6",  from: "transcript",    to: "draft_note" },
    { id: "flow_7",  from: "draft_note",    to: "safety_check" },
    { id: "flow_8",  from: "safety_check",  to: "review_ui" },
    { id: "flow_9",  from: "review_ui",     to: "clinician" },
    { id: "flow_10", from: "clinician",     to: "decision" },
    { id: "flow_11", from: "decision",      to: "accept_out", name: "Accept" },
    { id: "flow_12", from: "decision",      to: "modify_out", name: "Modify" },
    { id: "flow_13", from: "decision",      to: "reject_out", name: "Reject" },
    { id: "flow_14", from: "accept_out",    to: "ehr" },
    { id: "flow_15", from: "modify_out",    to: "ehr" },
    { id: "flow_16", from: "reject_out",    to: "training_loop" },
    { id: "flow_17", from: "training_loop", to: "redraft" },
    { id: "flow_18", from: "redraft",       to: "draft_note", from_side: "bottom", to_side: "bottom" },
  ],
};
